// The autogenerated code is released under Public Domain.

// WARNING: This file has automatically been generated on Tue, 16 Oct 2018 02:42:19 EEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package vma

/*
#cgo CFLAGS: -I.. -DVK_NO_PROTOTYPES
#include "../vulkan/vulkan.h"
#include "vk_mem_alloc.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// AllocatorCreateFlagBits as declared in vma/vk_mem_alloc.h:1563
type AllocatorCreateFlagBits int32

// AllocatorCreateFlagBits enumeration from vma/vk_mem_alloc.h:1563
const ()

// RecordFlagBits as declared in vma/vk_mem_alloc.h:1603
type RecordFlagBits int32

// RecordFlagBits enumeration from vma/vk_mem_alloc.h:1603
const ()

// MemoryUsage as declared in vma/vk_mem_alloc.h:1857
type MemoryUsage int32

// MemoryUsage enumeration from vma/vk_mem_alloc.h:1857
const ()

// AllocationCreateFlagBits as declared in vma/vk_mem_alloc.h:1960
type AllocationCreateFlagBits int32

// AllocationCreateFlagBits enumeration from vma/vk_mem_alloc.h:1960
const ()

// PoolCreateFlagBits as declared in vma/vk_mem_alloc.h:2120
type PoolCreateFlagBits int32

// PoolCreateFlagBits enumeration from vma/vk_mem_alloc.h:2120
const ()
