// The autogenerated code is released under Public Domain.

// WARNING: This file has automatically been generated on Tue, 16 Oct 2018 02:42:19 EEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package vma provides Go bindings for vk_mem_alloc.h
*/
package vma
